pr: none
trigger: none
pool:
  vmImage: ubuntu-latest

stages:
  - stage: deploy
    displayName: 'Deploy Worker'
    jobs:
      - job: deployWorker
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Keboola DEV PS Team CI'
              scriptType: 'bash'
              scriptLocation: 'scriptPath'
              scriptPath: 'run-startup.sh'
            env:
              SUBSCRIPTION: $(SUBSCRIPTION)
              WORKER_NAME: $(WORKER_NAME)
              ADMIN_USERNAME: $(ADMIN_USERNAME)
              ADMIN_PASSWORD: $(ADMIN_PASSWORD)
              POOL_NAME: $(POOL_NAME)
              WORKER_LOCATION: $(WORKER_LOCATION)
              PAT_TOKEN: $(System.AccessToken)
