pr: none
trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: deploy
    displayName: 'Remove Worker'
    jobs:
      - job: deployWorker
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Keboola DEV PS Team CI(9577e289-304e-4165-abe0-91c933200878)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -Eeuo pipefail

                if [[ "$WORKER_NAME" == "pipeline-"* ]] ;
                then
                  envsubst < shutdown.sh > shutdown-replaced.sh
                  export SCRIPT_CONTENT=$(cat shutdown-replaced.sh | gzip -9 | base64 -w 0)
                  echo "Deregistering agent $WORKER_NAME\n"

                  az deployment group create --name "$WORKER_NAME" --resource-group "$WORKER_NAME" \
                      --subscription "$SUBSCRIPTION" --template-file ./template.json \
                      --parameters adminUsername="$ADMIN_USERNAME" adminPassword="$ADMIN_PASSWORD" \
                            scriptContent="$SCRIPT_CONTENT"
                  echo "Deleting deployment $WORKER_NAME\n"
                  az deployment group delete --name "$WORKER_NAME" --resource-group "$WORKER_NAME" --subscription "$SUBSCRIPTION"
                  az group delete --name "$WORKER_NAME" --subscription "$SUBSCRIPTION" --yes
                else
                  echo "'$WORKER_NAME' is not a valid worker name (must match 'pipeline-*')."
                  exit 1
                fi
            env:
              SUBSCRIPTION: $(SUBSCRIPTION)
              WORKER_NAME: $(WORKER_NAME)
              ADMIN_USERNAME: $(ADMIN_USERNAME)
              ADMIN_PASSWORD: $(ADMIN_PASSWORD)
              PAT_TOKEN: $(System.AccessToken)
