pr: none
trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: delete
    displayName: 'Remove Worker'
    jobs:
      - job: deleteWorker
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Keboola DEV PS Team CI(9577e289-304e-4165-abe0-91c933200878)'
              scriptType: 'bash'
              scriptLocation: 'scriptPath'
              scriptPath: 'run-shutdown.sh'
            env:
              SUBSCRIPTION: $(SUBSCRIPTION)
              WORKER_NAME: $(WORKER_NAME)
              PAT_TOKEN: $(System.AccessToken)
